### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by OgelGames** [pandorabox-io/pandorabox_custom#29]
This mod is actually in an "interesting" place without a license, at least by what is stated here: https://opensource.guide/legal/

> If you don’t apply an open source license, everybody who contributes to your project also becomes an exclusive copyright holder of their work. That means nobody can **use**, copy, distribute, or modify their contributions – and that “nobody” includes you.

Which also means those copycat servers that use this mod are actually doing so illegally... 👀

**Comment by S-S-X** [comment]
All contributors have to agree with it, again I'd suggest full freedom license like MIT.

At least @SwissalpS @MilesBDyson @Panquesito7 @coil0 @BuckarooBanzay @6r1d 

Then, if strictly following rules, there's few options if someone does not agree:
* Use different license for their part
* Or use different license for whole thing
* Or remove everything they've added

Anyway, in this case I believe it is completely safe to keep stuff until author has voiced their opinion. Keeping in mind that content can always be removed if conflicts with contributors happen.

I am willing to grant usage of my work under MIT license terms https://choosealicense.com/licenses/mit/
I could also consider other additional licenses if needed for license compatibility.

**Comment by MilesBDyson** [comment]
I have no clams to any code i added or modified for this server/game. any thing i do is really WTF so feel free to do with what you like as far as i am concerned. this includes the colors.txt file i put together for the map as well.

thanks :)

**Comment by Panquesito7** [comment]
I'm granting the use of my work under the MIT license (same as @S-S-X). 🙂

**Comment by 6r1d** [comment]
I'm granting the use of my work under the MIT license and will be happy to see it here!

**Comment by BuckarooBanzay** [comment]
> Which also means those copycat servers that use this mod are actually doing so illegally... eyes

Hehe, nice find :+1: 

> All contributors have to agree with it, again I'd suggest full freedom license like MIT.

Same here: i'm granting the use of my work under the MIT license

**Comment by SwissalpS** [comment]
I hereby grant the use of my work under the MIT license.

**Comment by Panquesito7** [comment]
@coil0 has been quite inactive in GitHub. It seems he hasn't made any other contributions in Pandora Box, too :/

**Comment by 6r1d** [comment]
@Panquesito7 I think we can find him through Discord :-)

**Comment by BuckarooBanzay** [comment]
> @coil0 has been quite inactive in GitHub. It seems he hasn't made any other contributions in Pandora Box, too. confused

It happens :shrug: 

> @Panquesito7 I think we can find him through Discord :-)

In the worst case we can go with the MIT license, i don't think he minds...

**Comment by S-S-X** [comment]
> In the worst case we can go with the MIT license, i don't think he minds...

Also if very unlikely thing happens and he does then he can just ask to remove whatever he added there. Also should not really be that big problem as someone else did not bring code here without licenses (in that case it definitely would not be okay), if you are paranoid and want to be extra safe then just add exception for parts coil0 added.

**Comment by coil0** [comment]
I’m happy for my contributions to be licensed under MIT/Expat. Sorry for the delay. :slightly_smiling_face:
