### ISSUE TITLE
Add XP limits for spacecannons

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/pandorabox_custom#36]
To prevent abuse of very powerful weapons add some XP limit for cannon usage.

Before it was limited to 100k XP because of warzone limit.
After warzone restriction was removed there was still some limits through travel XP limits.
Now related issue #35 would practically remove XP limits completely.

**Comment by S-S-X** [comment]
Personally I think 100k XP is not too high requirement but maybe could be lower too but has to be something more than 0.

**Comment by BuckarooBanzay** [comment]
the `spacecannon_unrestricted` priv can be auto-granted for that (related: 863fd6e987533fb54d5fc690331acc4eb7f7efc9)
